name: notes
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  sqflite: ^2.3.3
  change_app_package_name: ^1.1.0
  url_launcher: ^6.3.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  pin_code_fields: ^8.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          style: italic
